/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import java.io.IOException;
import java.net.InetSocketAddress;
import java.nio.channels.SelectionKey;
import java.nio.channels.Selector;
import java.nio.channels.ServerSocketChannel;
import java.nio.channels.SocketChannel;
import java.util.Set;

import java.util.Iterator;

public class App {
  public String getGreeting() {
      return "Hello World!";
  }
  public void run(){
    try{
      Selector selector = Selector.open();
      ServerSocketChannel serverSocketChannel = ServerSocketChannel.open();
      serverSocketChannel.configureBlocking(false);
      InetSocketAddress inetSocketAddress = new InetSocketAddress(8000);
      serverSocketChannel.bind(inetSocketAddress);
      System.out.println("Socket Server started at port 8000");
      serverSocketChannel.register(selector, SelectionKey.OP_ACCEPT);
      while(true) {
        int readyCount = selector.select();
        if(readyCount == 0){
          continue;
        }
        Set<SelectionKey> readyKeySet = selector.selectedKeys();
        Iterator<SelectionKey> iterator = readyKeySet.iterator();
        while(iterator.hasNext()){
          SelectionKey key = iterator.next();
          iterator.remove();
          if(key.isAcceptable()){
            System.out.println("Accepting connection");
            ServerSocketChannel server = (ServerSocketChannel) key.channel();
            SocketChannel client = server.accept();
            client.configureBlocking(false);
            SelectionKey clientKey = client.register(selector, SelectionKey.OP_READ);
            clientKey.attach(new StringBuilder());
            continue;
          }
        }
      }
    }catch(IOException e){
      e.printStackTrace();
    }
  }

  public static void main(String[] args) {
      System.out.println(new App().getGreeting());
  }
}
